/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UsrInterface;

import java.io.FileOutputStream;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.proteanit.sql.DbUtils;
import net.proteanit.sql.DbUtils;
import com.itextpdf.text.Document;
import com.itextpdf.text.Font;
import com.itextpdf.text.FontFactory;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.pdf.PdfWriter;
import java.io.FileOutputStream;
import java.sql.SQLException;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JTextField;

 
public class Booking extends javax.swing.JFrame {
    Staff_Fucntion StaffFunc=new Staff_Fucntion();
    RoomFunc RmFunc=new RoomFunc();
    BookingFunc BkFunc=new BookingFunc();
    PaymentFunc PayFunc=new PaymentFunc();
    BookingInfo aBooking;
    Payment aPayment;
    ArrayList <BookingInfo> BookingList=new ArrayList <BookingInfo>();
    DBConnect dbc;
    Connection conn=null;
     ResultSet rs=null;
     PreparedStatement pst=null;
     String guestName,bookingID,NS,RmtypeName;
     int NightStay,RoomType,TotalBill;
    /**
     * Creates new form Booking
     */
    public Booking() {
        initComponents();
        
        String connectionUrl = "jdbc:mysql://localhost/"+"hotelsystm";
       
            try{
            conn = DriverManager.getConnection(connectionUrl,"root","");
             System.out.println("ok");
            }catch(Exception e){
                 System.out.println("no");
            }
             //System.out.println("ok");
            updateTableGuest();
            updateTable();
            updateTableFreeROOM();
            updateTableFreeStaff();
            updatePayMethodTable();
            updateFullInfoTable();
            updatePayIncomp();
            updatePaymentTable();
                    
            
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel4 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        Search_booking = new javax.swing.JTextField();
        jScrollPane5 = new javax.swing.JScrollPane();
        ChkInTable = new javax.swing.JTable();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        Ser_BkID = new javax.swing.JTextField();
        Ser_RmNUm = new javax.swing.JTextField();
        Ser_Staff = new javax.swing.JTextField();
        Ser_NOG = new javax.swing.JTextField();
        CheckInBut = new javax.swing.JButton();
        CheckOutBut = new javax.swing.JButton();
        DeleteBkingBut = new javax.swing.JButton();
        UpdateBkingBut = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        Ser_ChckIn = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        Ser_chckOut = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        PayMethod = new javax.swing.JTextField();
        Amount = new javax.swing.JTextField();
        DateOfPay = new javax.swing.JTextField();
        Bking_pay = new javax.swing.JTextField();
        PaymentADD = new javax.swing.JButton();
        jScrollPane6 = new javax.swing.JScrollPane();
        PaymentTable = new javax.swing.JTable();
        jLabel21 = new javax.swing.JLabel();
        jScrollPane7 = new javax.swing.JScrollPane();
        PayMehtodTab = new javax.swing.JTable();
        jLabel22 = new javax.swing.JLabel();
        jScrollPane10 = new javax.swing.JScrollPane();
        Payment_Incomplete = new javax.swing.JTable();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        from = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        to = new javax.swing.JTextField();
        jScrollPane8 = new javax.swing.JScrollPane();
        SearchByDate = new javax.swing.JTable();
        jLabel35 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane9 = new javax.swing.JScrollPane();
        FullInfo = new javax.swing.JTable();
        gname = new javax.swing.JTextField();
        NOS = new javax.swing.JTextField();
        RomTy = new javax.swing.JTextField();
        BkingID = new javax.swing.JTextField();
        Bill = new javax.swing.JButton();
        bl = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        NsLabel = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        RmtypeLabel = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        BkingIDLabel = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        GstnameLabel = new javax.swing.JLabel();
        jLabel47 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        B_guestID = new javax.swing.JTextField();
        B_RmNum = new javax.swing.JTextField();
        B_Staff = new javax.swing.JTextField();
        NOG = new javax.swing.JTextField();
        BookingDate = new javax.swing.JTextField();
        BOOK = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        BookingTable = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        GSt_Table_bking = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        Bking_Staff = new javax.swing.JTable();
        jScrollPane4 = new javax.swing.JScrollPane();
        BKing_RM = new javax.swing.JTable();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel10.setText("Search Booking ID");

        Search_booking.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Search_bookingActionPerformed(evt);
            }
        });
        Search_booking.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                Search_bookingKeyReleased(evt);
            }
        });

        ChkInTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        ChkInTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ChkInTableMouseClicked(evt);
            }
        });
        jScrollPane5.setViewportView(ChkInTable);

        jLabel11.setText("Booking ID");

        jLabel12.setText("Room Number");

        jLabel13.setText("Staff");

        jLabel14.setText("Number Of Guest");

        CheckInBut.setText("Check In");
        CheckInBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CheckInButActionPerformed(evt);
            }
        });

        CheckOutBut.setText("Check Out");
        CheckOutBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CheckOutButActionPerformed(evt);
            }
        });

        DeleteBkingBut.setText("Delete");
        DeleteBkingBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteBkingButActionPerformed(evt);
            }
        });

        UpdateBkingBut.setText("Update");
        UpdateBkingBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateBkingButActionPerformed(evt);
            }
        });

        jLabel15.setText("Check In");

        jLabel16.setText("Check Out");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel10)
                        .addComponent(Search_booking)
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 520, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Ser_BkID, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel16)
                                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel15)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(Ser_ChckIn)
                                    .addComponent(Ser_chckOut)
                                    .addComponent(Ser_NOG, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Ser_RmNUm, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel13)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Ser_Staff, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(182, 182, 182)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(CheckOutBut)
                            .addComponent(CheckInBut, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(DeleteBkingBut, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(UpdateBkingBut, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(722, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel10)
                .addGap(18, 18, 18)
                .addComponent(Search_booking, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(Ser_BkID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(Ser_RmNUm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addComponent(CheckInBut)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(CheckOutBut)))
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel13)
                    .addComponent(Ser_Staff, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(Ser_NOG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(Ser_ChckIn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DeleteBkingBut))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Ser_chckOut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(UpdateBkingBut))
                    .addComponent(jLabel16))
                .addContainerGap(192, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Checkin", jPanel4);

        jLabel17.setText("Payment Method");

        jLabel18.setText("Amount");

        jLabel19.setText("Date ");

        jLabel20.setText("Booking ID");

        PaymentADD.setText("ADD");
        PaymentADD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PaymentADDActionPerformed(evt);
            }
        });

        PaymentTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane6.setViewportView(PaymentTable);

        jLabel21.setText("Payments");

        PayMehtodTab.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane7.setViewportView(PayMehtodTab);

        jLabel22.setText("Payment Methods");

        Payment_Incomplete.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane10.setViewportView(Payment_Incomplete);

        jLabel33.setText("Incomplete Payment");

        jLabel34.setText("Format: MM-DD-YY");

        jLabel36.setText("Insert Payment Information");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel18)
                                    .addComponent(jLabel19))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(Amount, javax.swing.GroupLayout.DEFAULT_SIZE, 296, Short.MAX_VALUE)
                                    .addComponent(DateOfPay)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel20)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel36)
                                            .addComponent(jLabel17))))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(PayMethod, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(11, 11, 11)
                                        .addComponent(Bking_pay)))))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel34)
                        .addGap(36, 36, 36))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(189, 189, 189)
                                .addComponent(PaymentADD))
                            .addComponent(jLabel21)
                            .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel22)
                    .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel33))
                .addGap(198, 198, 198))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(jLabel22))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jLabel36)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel17)
                            .addComponent(PayMethod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel18)
                            .addComponent(Amount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel19)
                            .addComponent(DateOfPay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel34))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel20)
                            .addComponent(Bking_pay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(43, 43, 43)
                        .addComponent(PaymentADD))
                    .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jLabel21)
                        .addGap(27, 27, 27))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel33)
                        .addGap(18, 18, 18)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane10, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 290, Short.MAX_VALUE))
                .addContainerGap(131, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Payment", jPanel1);

        jLabel23.setText("Date");

        jLabel24.setText("From");

        from.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fromActionPerformed(evt);
            }
        });

        jLabel25.setText("To");

        to.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                toKeyReleased(evt);
            }
        });

        SearchByDate.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane8.setViewportView(SearchByDate);

        jLabel35.setText("(Formant: MM-DD-YY)");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel23)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel35))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel24)
                            .addComponent(from, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel25)
                            .addComponent(to, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 1172, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(67, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(jLabel35))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel24)
                    .addComponent(jLabel25))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(from, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(to, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(222, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Search", jPanel2);

        FullInfo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        FullInfo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                FullInfoMouseClicked(evt);
            }
        });
        jScrollPane9.setViewportView(FullInfo);

        gname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gnameActionPerformed(evt);
            }
        });

        NOS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NOSActionPerformed(evt);
            }
        });

        RomTy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RomTyActionPerformed(evt);
            }
        });

        Bill.setText("Generate Bill");
        Bill.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BillActionPerformed(evt);
            }
        });

        bl.setText("jLabel38");

        jLabel38.setText("Guest Name");

        jLabel39.setText("Night Stay");

        jLabel40.setText("Room Type ID");

        jLabel41.setText("Bookig ID");

        jLabel42.setText("Total Bill  :");

        jLabel43.setText("Night Stay:");

        NsLabel.setText("jLabel44");

        jLabel44.setText("Room type:");

        RmtypeLabel.setText("jLabel45");

        jLabel45.setText("Booking ID:");

        BkingIDLabel.setText("jLabel46");

        jLabel46.setText("Guest Name:");

        GstnameLabel.setText("jLabel47");

        jLabel47.setForeground(new java.awt.Color(0, 0, 255));
        jLabel47.setText("Bill Information:");

        jButton2.setText("Print");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jScrollPane9, javax.swing.GroupLayout.DEFAULT_SIZE, 1253, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel38)
                            .addComponent(jLabel39)
                            .addComponent(jLabel40)
                            .addComponent(jLabel41))
                        .addGap(30, 30, 30)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(BkingID, javax.swing.GroupLayout.DEFAULT_SIZE, 103, Short.MAX_VALUE)
                            .addComponent(RomTy, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(NOS)
                            .addComponent(gname))
                        .addGap(164, 164, 164)
                        .addComponent(Bill)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                                            .addComponent(jLabel46)
                                            .addGap(18, 18, 18))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                                            .addComponent(jLabel45)
                                            .addGap(25, 25, 25)))
                                    .addGroup(jPanel5Layout.createSequentialGroup()
                                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel43)
                                            .addComponent(jLabel44)
                                            .addComponent(jLabel42))
                                        .addGap(24, 24, 24)))
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(RmtypeLabel)
                                    .addComponent(BkingIDLabel)
                                    .addComponent(GstnameLabel)
                                    .addComponent(NsLabel)
                                    .addComponent(bl))
                                .addGap(475, 475, 475))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                                .addComponent(jLabel47)
                                .addGap(602, 602, 602))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                                .addComponent(jButton2)
                                .addGap(299, 299, 299))))))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 343, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52)
                .addComponent(jLabel47)
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(gname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel38)
                    .addComponent(jLabel46)
                    .addComponent(GstnameLabel))
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(NOS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel39))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Bill)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(RomTy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel40)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(BkingID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel41)))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel45)
                            .addComponent(BkingIDLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel44)
                            .addComponent(RmtypeLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel43)
                            .addComponent(NsLabel))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel42)
                            .addComponent(bl))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 97, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addGap(93, 93, 93))
        );

        jTabbedPane2.addTab("Full Info", jPanel5);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1273, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 762, Short.MAX_VALUE)
        );

        jTabbedPane2.addTab("Billing", jPanel6);

        jLabel1.setText("Guest ID");

        jLabel2.setText("Room Number");

        jLabel3.setText("Staff");

        jLabel4.setText("Number Of guest");

        jLabel5.setText("Booking Date");

        B_guestID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_guestIDActionPerformed(evt);
            }
        });

        BOOK.setText("Book");
        BOOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BOOKActionPerformed(evt);
            }
        });

        BookingTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(BookingTable);

        jLabel6.setText("Bookings");

        GSt_Table_bking.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(GSt_Table_bking);

        jLabel7.setText("Guest List");

        Bking_Staff.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(Bking_Staff);

        BKing_RM.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane4.setViewportView(BKing_RM);

        jLabel8.setText("Available Rooms");

        jLabel9.setText("Available Staffs");

        jLabel26.setText("Insert Booking Information");

        jLabel27.setForeground(new java.awt.Color(255, 0, 0));
        jLabel27.setText("Dont forget to enter Information in * fields");

        jLabel28.setForeground(new java.awt.Color(255, 0, 0));
        jLabel28.setText("*");

        jLabel29.setForeground(new java.awt.Color(255, 0, 0));
        jLabel29.setText("*");

        jLabel30.setForeground(new java.awt.Color(255, 0, 0));
        jLabel30.setText("*");

        jLabel31.setForeground(new java.awt.Color(255, 0, 0));
        jLabel31.setText("*");

        jLabel32.setForeground(new java.awt.Color(255, 0, 0));
        jLabel32.setText("*");

        jLabel37.setText("Format: MM-DD-YY");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(256, 256, 256)
                .addComponent(BOOK)
                .addGap(34, 34, 34))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 644, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel26)
                    .addComponent(jLabel27)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addGap(29, 29, 29)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel37)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(B_guestID, javax.swing.GroupLayout.DEFAULT_SIZE, 350, Short.MAX_VALUE)
                                    .addComponent(B_RmNum)
                                    .addComponent(B_Staff)
                                    .addComponent(NOG)
                                    .addComponent(BookingDate))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel28)
                                    .addComponent(jLabel29)
                                    .addComponent(jLabel30)
                                    .addComponent(jLabel31)
                                    .addComponent(jLabel32))))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 77, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 480, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(34, 34, 34))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9))
                        .addContainerGap())))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(jLabel26))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel27)
                                .addGap(19, 19, 19)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel1)
                                    .addComponent(B_guestID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel28))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel2)
                                    .addComponent(B_RmNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel29))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel3)
                                    .addComponent(B_Staff, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel30))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel4)
                                    .addComponent(NOG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel31))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel5)
                                    .addComponent(BookingDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel32))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel37))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(BOOK)
                        .addGap(31, 31, 31)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(220, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Bookings", jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane2)
                .addGap(27, 27, 27))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane2)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        try{
            Document document=new Document();
            PdfWriter.getInstance(document, new FileOutputStream("Report.pdf"));
            document.open();
            document.add(new Paragraph("                               Trinoyon Hotel",FontFactory.getFont(FontFactory.TIMES_BOLD,18,Font.BOLD)));
            document.add(new Paragraph("                                           Mirpur,Dhaka-1216",FontFactory.getFont(FontFactory.TIMES_BOLD,12,Font.BOLD)));
            document.add(new Paragraph("                                               Tel-01666666666",FontFactory.getFont(FontFactory.TIMES_BOLD,12,Font.BOLD)));
            document.add(new Paragraph("Invoice No : ",FontFactory.getFont(FontFactory.TIMES,12,Font.NORMAL)));

            document.add(new Paragraph("----------------------------------------------------------------------------------------------------------------------------------"));
            document.add(new Paragraph("----------------------------------------------------------------------------------------------------------------------------------"));

            document.add(new Paragraph(""));
            document.add(new Paragraph(""));
            document.add(new Paragraph(""));
            document.add(new Paragraph(""));
            document.add(new Paragraph(""));
            document.add(new Paragraph(""));
            document.add(new Paragraph("----------------------------------------------------------------------------------------------------------------------------------"));
            document.add(new Paragraph("                                                                                                        Guest name   :"+guestName,FontFactory.getFont(FontFactory.TIMES_BOLD,12,Font.BOLD)));
            document.add(new Paragraph("                                                                                                       Booking ID   :"+bookingID,FontFactory.getFont(FontFactory.TIMES_BOLD,12,Font.BOLD)));
            document.add(new Paragraph("                                                                                                      Night Stay   :"+NightStay,FontFactory.getFont(FontFactory.TIMES_BOLD,12,Font.BOLD)));
            document.add(new Paragraph("                                                                                                     Room Type   :"+RmtypeName,FontFactory.getFont(FontFactory.TIMES_BOLD,12,Font.BOLD)));
            document.add(new Paragraph("----------------------------------------------------------------------------------------------------------------------------------"));
            document.add(new Paragraph("                                                                                                       Total bill   :"+TotalBill,FontFactory.getFont(FontFactory.TIMES_BOLD,12,Font.BOLD)));

            document.close();
        }catch(Exception e)
        {

        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void BillActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BillActionPerformed
        int bill=0;
        NightStay= Integer.parseInt (NOS.getText());
        RoomType= Integer.parseInt (RomTy.getText());
        if(RoomType==53){
            if(NightStay==0){
                NightStay=NightStay+1;
                bill=NightStay*1200;
                System.out.println("Bill 20: "+bill);
                
            }
            else{
                bill=NightStay*1200;
            }
            bl.setText(String.valueOf(bill));
            GstnameLabel.setText(guestName);
            NsLabel.setText(String.valueOf(NightStay));
            BkingIDLabel.setText(bookingID);
            RmtypeLabel.setText(RmtypeName);
            System.out.println("Bill : "+bill);
        }
        if(RoomType==52){
            if(NightStay==0){
                NightStay=NightStay+1;
                bill=NightStay*800;
            }
            else{
                bill=NightStay*800;
            }
            bl.setText(String.valueOf(bill));
            GstnameLabel.setText(guestName);
            NsLabel.setText(String.valueOf(NightStay));
            BkingIDLabel.setText(bookingID);
            RmtypeLabel.setText(RmtypeName);
            System.out.println("Bill : "+bill);
        }
        if(RoomType==54){
            if(NightStay==0){
                NightStay=NightStay+1;
                bill=NightStay*1000;
            }
            else{
                bill=NightStay*1000;
            }
            bl.setText(String.valueOf(bill));
            GstnameLabel.setText(guestName);
            NsLabel.setText(String.valueOf(NightStay));
            BkingIDLabel.setText(bookingID);
            RmtypeLabel.setText(RmtypeName);
            System.out.println("Bill : "+bill);
        }
        if(RoomType==55){
            if(NightStay==0){
                NightStay=NightStay+1;
                bill=NightStay*1500;
            }
            else{
                bill=NightStay*1500;
            }
            bl.setText(String.valueOf(bill));
            GstnameLabel.setText(guestName);
            NsLabel.setText(String.valueOf(NightStay));
            BkingIDLabel.setText(bookingID);
            RmtypeLabel.setText(RmtypeName);
            System.out.println("Bill : "+bill);
        }
        if(RoomType==56){
            if(NightStay==0){
                NightStay=NightStay+1;
                bill=NightStay*3000;
            }
            else{
                bill=NightStay*3000;
            }
            bl.setText(String.valueOf(bill));
            GstnameLabel.setText(guestName);
            NsLabel.setText(String.valueOf(NightStay));
            BkingIDLabel.setText(bookingID);
            RmtypeLabel.setText(RmtypeName);
            System.out.println("Bill : "+bill);
        }
        if(RoomType==59){
            if(NightStay==0){
                NightStay=NightStay+1;
                bill=NightStay*5000;
            }
            else{
                bill=NightStay*5000;
            }
            bl.setText(String.valueOf(bill));
            GstnameLabel.setText(guestName);
            NsLabel.setText(String.valueOf(NightStay));
            BkingIDLabel.setText(bookingID);
            RmtypeLabel.setText(RmtypeName);
            System.out.println("Bill : "+bill);
        }
        if(RoomType==61){
            if(NightStay==0){
                NightStay=NightStay+1;
                bill=NightStay*15000;
            }
            else{
                bill=NightStay*15000;
            }
            bl.setText(String.valueOf(bill));
            GstnameLabel.setText(guestName);
            NsLabel.setText(String.valueOf(NightStay));
            BkingIDLabel.setText(bookingID);
            RmtypeLabel.setText(RmtypeName);
            System.out.println("Bill : "+bill);
        }
        System.out.println("Bill : "+bill);
        TotalBill=bill;
        // TODO add your handling code here:
    }//GEN-LAST:event_BillActionPerformed

    private void NOSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NOSActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NOSActionPerformed

    private void FullInfoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FullInfoMouseClicked

        try{
            int row=FullInfo.getSelectedRow();
            String Table_click=(FullInfo.getModel().getValueAt(row, 0).toString());

            String sql="select Guest.GuestID,Booking.BookingID,Guest.FirstName+' '+ Guest.LastName as 'Guest Name',Telephone,Address,CheckIn,Checkout,DATEDIFF(DAY,CheckIn,Checkout) as 'Night Stay',NumberOfguest,Booking.RoomNum,RoomType.RmTypeID,RoomType.RmType\n" +
            "             from Guest,Booking,Room,RoomType,Staff\n" +
            "             where Guest.GuestID=Booking.GuestID and Booking.RoomNum=Room.RoomNum and Booking.StaffID=Staff.StaffID and Room.RmtypeID=RoomType.RmTypeID and Guest.GuestID='"+Table_click+"'";
            //String connectionUrl = "jdbc:sqlserver://localhost:1433;user=Abir;password=12345;" +
            //    "databaseName=HotelProject;";
            pst=conn.prepareCall(sql);
            rs=pst.executeQuery();

            if(rs.next()){
                guestName=rs.getString("Guest Name");
                NightStay=Integer.parseInt(rs.getString("Night Stay"));
                NS=rs.getString("Night Stay");
                RoomType=Integer.parseInt (rs.getString("RmTypeID"));
                System.out.println("Roomtype "+RoomType);
                bookingID=rs.getString("BookingID");
                RmtypeName=rs.getString("RmType");

                gname.setText(guestName);
                NOS.setText(NS);
                this.RomTy.setText(rs.getString("RmTypeID"));
                BkingID.setText(bookingID);

            }
        }
        catch(Exception e){

        }
        // TODO add your handling code here:
    }//GEN-LAST:event_FullInfoMouseClicked

    private void toKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_toKeyReleased
        // TODO add your handling code here:
        try{

            String sql="select Guest.GuestID,Guest.FirstName+' '+ Guest.LastName as 'Guest Name',Telephone,Addresss,CheckIn,Checkout,NumberOfguest,Booking.RoomNum,RoomType.RmType   from Guest,Booking,Room,RoomType,Staff  where Guest.GuestID=Booking.GuestID and Booking.RoomNum=Room.RoomNum and Booking.StaffID=Staff.StaffID and Room.RmtypeID=RoomType.RmTypeID and CheckIn between ? and ?";
            pst=conn.prepareStatement(sql);
            pst.setString(1,from.getText() );
            pst.setString(2,to.getText() );
            rs=pst.executeQuery();

            SearchByDate.setModel(DbUtils.resultSetToTableModel(rs));
        }catch(Exception e){

        }

    }//GEN-LAST:event_toKeyReleased

    private void fromActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fromActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fromActionPerformed

    private void PaymentADDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PaymentADDActionPerformed
        try{
            aPayment=new Payment(Integer.parseInt(PayMethod.getText()),Integer.parseInt( Amount.getText()),DateOfPay.getText(),Integer.parseInt(Bking_pay.getText())
            );
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "You didnt full fill all Information field ");
        }
        try {
            //studentList.add(aStudent);
            //Operation ope;
            PayFunc.saveInvoice(aPayment);

        } catch (ClassNotFoundException ex) {

        }

        updateTableGuest();
        updateTable();
        updateTableFreeROOM();

        JOptionPane.showMessageDialog(null, "ok");
        updatePaymentTable();
        updatePayIncomp();
        // TODO add your handling code here:
    }//GEN-LAST:event_PaymentADDActionPerformed

    private void UpdateBkingButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateBkingButActionPerformed

        try{
            String BookingID=Ser_BkID.getText();
            String RmNum=Ser_RmNUm.getText();
            String Staff=Ser_Staff.getText();
            String NuOG=Ser_NOG.getText();

            String sql="update Booking set RoomNum='"+RmNum+"',StaffID='"+Staff+"',NumberOfguest='"+NuOG+"' where BookingID='"+BookingID+"'";

            pst=conn.prepareCall(sql);

            pst.execute();
            updateTable();
            JOptionPane.showMessageDialog(null,"Updated");
            updateFullInfoTable();
            updatePayIncomp();
            updateTable();
            updatePayIncomp();

        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_UpdateBkingButActionPerformed

    private void DeleteBkingButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteBkingButActionPerformed

        int confirmDialg=JOptionPane.showConfirmDialog(null,"Do tou really want to delete tha data?","Delete",JOptionPane.YES_NO_OPTION);
        if(confirmDialg==0){

            try{
                String n=Ser_BkID.getText();
                String sql="delete from Booking where BookingID="+n;
                 PreparedStatement preparedStmt = conn.prepareStatement(sql);
                preparedStmt.execute();
               /* pst=conn.prepareCall(sql);
                pst.setString(1, Ser_BkID.getText());
                rs=pst.executeQuery(sql);*/
                updateTable();
                int serRoom=Integer.parseInt(Ser_RmNUm.getText());
                String sqlRM="update Room set Availability='YES' where RoomNum='"+serRoom+"'";

                pst=conn.prepareCall(sqlRM);
                pst.execute();
                JOptionPane.showMessageDialog(null,"Deleted");
            }
            catch(Exception e){

            }
        }
        else{

        }
        // TODO add your handling code here:
    }//GEN-LAST:event_DeleteBkingButActionPerformed

    private void CheckOutButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CheckOutButActionPerformed
        // TODO add your handling code here:
        try{

            int SerID=Integer.parseInt(Ser_BkID.getText());
            String sql="update Booking set CheckOut=GETDATE() where BookingID='"+SerID+"'";

            pst=conn.prepareCall(sql);

            pst.execute();

            int serRoom=Integer.parseInt(Ser_RmNUm.getText());
            String sqlRM="update Room set Availability='YES' where RoomNum='"+serRoom+"'";

            pst=conn.prepareCall(sqlRM);

            pst.execute();

            int UpStaf=Integer.parseInt(Ser_Staff.getText());
            String sqlStaf="update Staff set BookingTo=NULL where StaffID='"+UpStaf+"'";

            pst=conn.prepareCall(sqlStaf);

            pst.execute();

            updateTable();

            updateTableGuest();

            updateTableFreeROOM();
            updateTableFreeStaff();
            JOptionPane.showMessageDialog(null,"Updated");

        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
        }
        updateTableSearch();
    }//GEN-LAST:event_CheckOutButActionPerformed

    private void CheckInButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CheckInButActionPerformed
        try{

            int SerID=Integer.parseInt(Ser_BkID.getText());
            String sql="update Booking set CheckIn=GETDATE() where BookingID='"+SerID+"'";

            pst=conn.prepareCall(sql);

            pst.execute();

            int serRoom=Integer.parseInt(Ser_RmNUm.getText());
            String sqlRM="update Room set Availability='NO' where RoomNum='"+serRoom+"'";

            pst=conn.prepareCall(sqlRM);

            pst.execute();

            int UpStaf=Integer.parseInt(Ser_Staff.getText());
            String sqlStaf="update Staff set BookingTo='"+SerID+"' where StaffID='"+UpStaf+"'";

            pst=conn.prepareCall(sqlStaf);

            pst.execute();

            updateTable();
            updateTableGuest();

            updateTableFreeROOM();
            updateTableFreeStaff();
            JOptionPane.showMessageDialog(null,"Updated");

        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_CheckInButActionPerformed

    private void ChkInTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ChkInTableMouseClicked
        try{
            int row=ChkInTable.getSelectedRow();
            String Table_click=(ChkInTable.getModel().getValueAt(row, 0).toString());
            String sql="select * from Booking where BookingID='"+Table_click+"'";
            pst=conn.prepareCall(sql);
            rs=pst.executeQuery();

            if(rs.next()){
                Ser_BkID.setText(rs.getString("BookingID"));
                Ser_RmNUm.setText(rs.getString("RoomNum"));
                Ser_Staff.setText(rs.getString("StaffID"));
                Ser_NOG.setText(rs.getString("NumberOfguest"));
                Ser_ChckIn.setText(rs.getString("CheckIn"));
                Ser_chckOut.setText(rs.getString("CheckOut"));

            }
        }
        catch(Exception e){

        }

        // TODO add your handling code here:
    }//GEN-LAST:event_ChkInTableMouseClicked

    private void Search_bookingKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Search_bookingKeyReleased

        try{

            String sql="select * from Booking where BookingID=?";
            pst=conn.prepareStatement(sql);
            pst.setString(1,Search_booking.getText() );
            rs=pst.executeQuery();

            ChkInTable.setModel(DbUtils.resultSetToTableModel(rs));
        }catch(Exception e){

        }

        // TODO add your handling code here:
    }//GEN-LAST:event_Search_bookingKeyReleased

    private void Search_bookingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Search_bookingActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Search_bookingActionPerformed

    private void BOOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BOOKActionPerformed

        try{
            aBooking=new BookingInfo(Integer.parseInt(B_guestID.getText()),
                  Integer.parseInt( B_Staff.getText()),Integer.parseInt(B_RmNum.getText()),
                    Integer.parseInt(NOG.getText()),BookingDate.getText()
            );
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "You didnt full fill all Information field ");
        }
        try {
            //studentList.add(aStudent);
            //Operation ope;
            BkFunc.saveInvoice(aBooking);

        } catch (ClassNotFoundException ex) {

        }
        try{

            String sqlRM="update Room set Availability='NO' where RoomNum='"+Integer.parseInt(B_RmNum.getText())+"'";

            pst=conn.prepareCall(sqlRM);

            pst.execute();

        }catch(Exception e){

        }

        updateTableGuest();
        updateTable();
        updateTableFreeROOM();

        // TODO add your handling code here:
    }//GEN-LAST:event_BOOKActionPerformed

    private void B_guestIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_guestIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_B_guestIDActionPerformed

    private void gnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_gnameActionPerformed

    private void RomTyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RomTyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RomTyActionPerformed
   
    private void updatePaymentTable(){
     
     try{
     String sql="select * from Payment";
     //String connectionUrl = "jdbc:sqlserver://localhost:1433;user=Abir;password=12345;" +
        //    "databaseName=HotelProject;";
            
          //  conn = DriverManager.getConnection(connectionUrl);
     pst=conn.prepareCall(sql);
     rs=pst.executeQuery();
     PaymentTable.setModel(DbUtils.resultSetToTableModel(rs));
     }catch(Exception e){
         
     }
    }
    
    private void updateFullInfoTable(){
     
     try{
     String sql="select Guest.GuestID,Guest.FirstName+' '+ Guest.LastName as 'Guest Name',Booking.BookingID,Telephone,Addresss,CheckIn,Checkout,DATEDIFF(DAY,CheckIn,Checkout) as 'Night Stay',NumberOfguest,Booking.RoomNum,RoomType.RmTypeID,RoomType.RmType\n" +
"             from Guest,Booking,Room,RoomType,Staff\n" +
"             where Guest.GuestID=Booking.GuestID and Booking.RoomNum=Room.RoomNum and Booking.StaffID=Staff.StaffID and Room.RmtypeID=RoomType.RmTypeID order by Booking.BookingID desc";
     //String connectionUrl = "jdbc:sqlserver://localhost:1433;user=Abir;password=12345;" +
        //    "databaseName=HotelProject;";
            
          //  conn = DriverManager.getConnection(connectionUrl);
     pst=conn.prepareCall(sql);
     rs=pst.executeQuery();
     FullInfo.setModel(DbUtils.resultSetToTableModel(rs));
     }catch(Exception e){
         
     }
    }
    
    private void updatePayIncomp(){
     
     try{
     String sql="select Booking.BookingID,Guest.GuestID,Guest.FirstName+' '+ Guest.LastName as 'Guest Name',Booking.CheckIn \n" +
"                  from Booking,Guest where Guest.GuestID=Booking.GuestID and Booking.BookingID in \n" +
"                  (select BookingID from Booking where CheckIn is not null\n" +
"                  except\n" +
"                  select BookingID from Payment )";
   
         
     pst=conn.prepareCall(sql);
     rs=pst.executeQuery();
     Payment_Incomplete.setModel(DbUtils.resultSetToTableModel(rs));
     }catch(Exception e){
         
     }
    }
    
    private void updatePayMethodTable(){
     
     try{
     String sql="select * from PaymentMethod";
  
     pst=conn.prepareCall(sql);
     rs=pst.executeQuery();
     PayMehtodTab.setModel(DbUtils.resultSetToTableModel(rs));
     }catch(Exception e){
         
     }
    }
    
    private void updateTable(){
     
     try{
     String sql="select * from Booking";
     //String connectionUrl = "jdbc:sqlserver://localhost:1433;user=Abir;password=12345;" +
        //    "databaseName=HotelProject;";
            
          //  conn = DriverManager.getConnection(connectionUrl);
     pst=conn.prepareCall(sql);
     rs=pst.executeQuery();
     BookingTable.setModel(DbUtils.resultSetToTableModel(rs));
     }catch(Exception e){
         
     }
    }
    private void updateTableSearch(){
     
     try{
     String sql="select * from Booking";
     //String connectionUrl = "jdbc:sqlserver://localhost:1433;user=Abir;password=12345;" +
        //    "databaseName=HotelProject;";
            
          //  conn = DriverManager.getConnection(connectionUrl);
     pst=conn.prepareCall(sql);
     rs=pst.executeQuery();
     BookingTable.setModel(DbUtils.resultSetToTableModel(rs));
     }catch(Exception e){
         
     }
    }
    
    private void updateTableGuest(){
     
     try{
     String sql="select GuestID,FirstName,LastName,Telephone from Guest order by GuestID desc";
     //String connectionUrl = "jdbc:sqlserver://localhost:1433;user=Abir;password=12345;" +
        //    "databaseName=HotelProject;";
            
          //  conn = DriverManager.getConnection(connectionUrl);
     pst=conn.prepareCall(sql);
     rs=pst.executeQuery();
     GSt_Table_bking.setModel(DbUtils.resultSetToTableModel(rs));
     }catch(Exception e){
         
     }
    }
    
    private void updateTableFreeROOM(){
     
     try{
     String sql="select RoomNum,RmType,Availability,Price from Room,RoomType where Room.RmTypeID=RoomType.RmTypeID and Availability='YES'";
     //String connectionUrl = "jdbc:sqlserver://localhost:1433;user=Abir;password=12345;" +
        //    "databaseName=HotelProject;";
            
          //  conn = DriverManager.getConnection(connectionUrl);
     pst=conn.prepareCall(sql);
     rs=pst.executeQuery();
     BKing_RM.setModel(DbUtils.resultSetToTableModel(rs));
     }catch(Exception e){
         
     }
    }
    
    private void updateTableFreeStaff(){
     
     try{
     String sql="select StaffID,JobType from Staff,JOB where Staff.JobID=JOB.JobID and BookingTo is null";
     //String connectionUrl = "jdbc:sqlserver://localhost:1433;user=Abir;password=12345;" +
        //    "databaseName=HotelProject;";
            
          //  conn = DriverManager.getConnection(connectionUrl);
     pst=conn.prepareCall(sql);
     rs=pst.executeQuery();
     Bking_Staff.setModel(DbUtils.resultSetToTableModel(rs));
     }catch(Exception e){
         
     }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Booking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Booking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Booking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Booking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Booking().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Amount;
    private javax.swing.JTable BKing_RM;
    private javax.swing.JButton BOOK;
    private javax.swing.JTextField B_RmNum;
    private javax.swing.JTextField B_Staff;
    private javax.swing.JTextField B_guestID;
    private javax.swing.JButton Bill;
    private javax.swing.JTextField BkingID;
    private javax.swing.JLabel BkingIDLabel;
    private javax.swing.JTable Bking_Staff;
    private javax.swing.JTextField Bking_pay;
    private javax.swing.JTextField BookingDate;
    private javax.swing.JTable BookingTable;
    private javax.swing.JButton CheckInBut;
    private javax.swing.JButton CheckOutBut;
    private javax.swing.JTable ChkInTable;
    private javax.swing.JTextField DateOfPay;
    private javax.swing.JButton DeleteBkingBut;
    private javax.swing.JTable FullInfo;
    private javax.swing.JTable GSt_Table_bking;
    private javax.swing.JLabel GstnameLabel;
    private javax.swing.JTextField NOG;
    private javax.swing.JTextField NOS;
    private javax.swing.JLabel NsLabel;
    private javax.swing.JTable PayMehtodTab;
    private javax.swing.JTextField PayMethod;
    private javax.swing.JButton PaymentADD;
    private javax.swing.JTable PaymentTable;
    private javax.swing.JTable Payment_Incomplete;
    private javax.swing.JLabel RmtypeLabel;
    private javax.swing.JTextField RomTy;
    private javax.swing.JTable SearchByDate;
    private javax.swing.JTextField Search_booking;
    private javax.swing.JTextField Ser_BkID;
    private javax.swing.JTextField Ser_ChckIn;
    private javax.swing.JTextField Ser_NOG;
    private javax.swing.JTextField Ser_RmNUm;
    private javax.swing.JTextField Ser_Staff;
    private javax.swing.JTextField Ser_chckOut;
    private javax.swing.JButton UpdateBkingBut;
    private javax.swing.JLabel bl;
    private javax.swing.JTextField from;
    private javax.swing.JTextField gname;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTextField to;
    // End of variables declaration//GEN-END:variables
}
