/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UsrInterface;

import java.awt.Color;
import javax.swing.JFrame;

 
public class UI extends javax.swing.JFrame {

    /**
     * Creates new form UI
     */
    public UI() {
        initComponents();
        getContentPane().setBackground(Color.white);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Bking_Icon = new javax.swing.JLabel();
        Guest_icon = new javax.swing.JLabel();
        staff_icon = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setForeground(new java.awt.Color(255, 255, 255));

        Bking_Icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UsrInterface/logos/Booking.png"))); // NOI18N
        Bking_Icon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Bking_IconMouseClicked(evt);
            }
        });

        Guest_icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UsrInterface/logos/guest.png"))); // NOI18N
        Guest_icon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Guest_iconMouseClicked(evt);
            }
        });

        staff_icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UsrInterface/logos/staff.png"))); // NOI18N
        staff_icon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                staff_iconMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(189, 189, 189)
                .addComponent(Guest_icon)
                .addGap(18, 18, 18)
                .addComponent(Bking_Icon)
                .addGap(18, 18, 18)
                .addComponent(staff_icon)
                .addContainerGap(319, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(197, 197, 197)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Bking_Icon)
                    .addComponent(Guest_icon)
                    .addComponent(staff_icon))
                .addContainerGap(200, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Bking_IconMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Bking_IconMouseClicked

            Booking boking=new Booking();
            boking.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_Bking_IconMouseClicked

    private void Guest_iconMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Guest_iconMouseClicked

         GuestWindow gstwin=new GuestWindow();
         gstwin.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_Guest_iconMouseClicked

    private void staff_iconMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_staff_iconMouseClicked
      StaffAndRoom Sr=new StaffAndRoom();
      Sr.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_staff_iconMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
               
                new UI().setVisible(true);
                
                //new UI().getContentPane().setBackground(Color.white);
            }
        });
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Bking_Icon;
    private javax.swing.JLabel Guest_icon;
    private javax.swing.JLabel staff_icon;
    // End of variables declaration//GEN-END:variables
}
